### ISSUE TITLE
Library example?

### ISSUE THREAD

**Issue by msuess** [fortanix/rust-sgx#143]
Hi!

I'm trying to build  a rust app that uses ecalls to call certain functions within an enclave, but I don't want to run the whole app inside one. I noticed that there is a `build_library` function in `enclave_runner` but I'm not sure how to compile my lib and convert it into an `sgxs` file. The only example in the repo that I could find was in `report-test/enclave/Makefile` but that was using gcc and sgxs-build. How do I build and convert a library using elf2sgxs so that I can load it using `EnclaveBuilder` and use `Library::call`?

**Comment by jethrogb** [comment]
There's currently no way to build a library enclave in Rust using the `x86_64-fortanix-unknown-sgx` target, see #90. Support for this is planned but we're still evaluating what this would look like. What is your use case and can you do it by using byte streams instead?

**Comment by msuess** [comment]
Hey Jethro, thanks for the quick response! I have a rust app that consumes messages from an external queue. I would like to execute enclave code based on these messages. Since the consumer is also calling foreign C functions I want to avoid embedding the whole app inside the enclave. I only need certain rust functions to be run inside the TEE and want to avoid networking between the consumer app and the enclave app. I hope that makes sense. Could you elaborate on how I could use byte streams to achieve this?

**Comment by jethrogb** [comment]
If you want everything in the same address space, you can use the `enclave-runner` crate directly instead of using the pre-compiled `ftxsgx-runner`. You can then intercept connect calls using a [`UsercallExtension`](https://edp.fortanix.com/docs/api/enclave_runner/struct.EnclaveBuilder.html#method.usercall_extension). There's an example at https://github.com/fortanix/rust-sgx/tree/master/examples/usercall-extension .

**Comment by msuess** [comment]
Thank you very much, this is exactly what I need!
