### ISSUE TITLE
GDB: automatically load binary at right address

### ISSUE THREAD

**Issue by jethrogb** [fortanix/rust-sgx#19]
Currently, when running `add-symbol-file`, you need to manually add the offset to the `.text` section. This could come from ELF instead.

**Comment by jethrogb** [comment]
@VardhanThigle can you piece out the appropriate information from your enhancements to the script so they can be used independently of sgxstate auto?

**Comment by VardhanThigle** [comment]
Sure.
We need 2 inputs to `add-symbol-file`  - file name and the offset at run-time. The run-time offset is calculated from offset of `.text` section in the ELF and the base address of TCS.

So should the new function be `add-sgx-symbol-file <tcs_address>`, or, 
just `add-sgx-symbol-file` assuming TCS address is present in rbx (for example case of an abort)?
I am leaning towards the former, since in case of later, `sgxstate auto` might be more preferred.
