### ISSUE TITLE
Memory allocation failed for Vec of size greater than 64KB?

### ISSUE THREAD

**Issue by zaxguo** [fortanix/rust-sgx#270]
Hi, 

Today I was trying to allocate a moderately large buffer (i.e. 80KB) for the TcpStream inside SGX to communicate with normal world but enclave panicked with a memory allocation failure. I thus wrote the below test function trying to figure out how large of a buffer enclave runtime can allocate before it crashed:
```rust
fn test_mem_alloc() {
    let mut mem = Vec::new();
    loop {
        mem.push(0u8);
        println!("Pushing {}", mem.len());
    }
}
```
I got shutdown at `65536` bytes (i.e. 64KB), shown in below printout:
```
Pushing 65534
Pushing 65535
Pushing 65536
Error in running enclave Enclave panicked: memory allocation of 131072 bytes failed
```
Does Fortanix has a limitation on how large of a Vec I can create or am I using the SDK in a wrong way?
Thanks.

**Comment by jethrogb** [comment]
When I run your code it goes up to 16777000+. This makes sense because the default heap size is 32MB. You can [adjust the heap size](https://edp.fortanix.com/docs/tasks/testing/).

**Comment by zaxguo** [comment]
Thanks. I tried to adjust it but no luck. Either smaller heap size or larger size, it always gets shutdown at 64KB. Any advice how I should address this issue?

**Comment by jethrogb** [comment]
Can you provide a complete crate that I can compile that exhibits the behavior?

**Comment by trevor-crypto** [comment]
@jethrogb 
Sorry to resurrect a dead issue, but I'm running into this error upon `TcpListener::accept()` where the heap allocation fails because it tries to allocate 2X my defined heap size ONLY when I send an empty HTTPS packet (`curl -k https://[bind_address]`) to the bound address, thus causing a panic. Does not happen when using HTTP or no scheme. 

I can't seem to reproduce the panic in a minimal working example. Tried multiple things to emulate our production code, like using multiple threads (but dummy ones that don't do anything).

Any ideas on how to debug this? I can't even get a backtrace working with the fortanix instructions.

I suspect the issue is starts from [here](https://github.com/rust-lang/rust/blob/45749b21b7fd836f6c4f11dd40376f7c83e2791b/library/std/src/sys/sgx/abi/usercalls/mod.rs#L111) (or is the `FIXME` relevant?), but it's really hard to trace down into the ABI since it's all macro generated.
