### ISSUE TITLE
Store thread name

### ISSUE THREAD

**Issue by jethrogb** [fortanix/rust-sgx#91]
`libstd/sys/sgx/thread.rs`
```rust
    pub fn set_name(_name: &CStr) {
        // FIXME: could store this pointer in TLS somewhere
    }
```

**Comment by vn971** [comment]
https://github.com/rust-lang/rust/pull/112646

**Comment by vn971** [comment]
As a result of the investigation, I've concluded that the issue is a result of wrong assumption:
It was thought that the thread name needs to be saved in the method called `Thread::set_name`. However, it seems that this method has a very different purpose: it signals the platform-specific (target-specific) code to set the thread name in the operating system.
However, in SGX, there is no strict concept of an operating system. And the name of the thread, as visible _inside_ SGX, is already stored by the platform-agnostic Rust code.
Therefore, the only action to take here is to document the situation and remove the FIXME marker.

**Comment by jethrogb** [comment]
Apparently already implemented
